'use client';
import { useCallback, useEffect, useState } from 'react';
import { FileText, Loader2, SquareTerminal, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { WorkspaceRunView } from '@/lib/workspace-runs/types';
export function WorkspaceRunPanel({ runId, slug, onContinue }: { runId: string | null; slug: string; onContinue?: () => void }) {
  const [run, setRun] = useState<WorkspaceRunView | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!runId) return; const res = await fetch(`/api/workspace-runs/${encodeURIComponent(runId)}?slug=${encodeURIComponent(slug)}`, { cache: 'no-store' }); if (!res.ok) { setError('Workspace state is unavailable.'); return; } setRun((await res.json() as { run: WorkspaceRunView }).run); setError(null); }, [runId, slug]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (!run || ['completed','failed','cancelled'].includes(run.status)) return; const timer = window.setInterval(() => void load(), 2500); return () => window.clearInterval(timer); }, [load, run]);
  const cancel = async () => { if (!runId) return; await fetch(`/api/workspace-runs/${encodeURIComponent(runId)}?slug=${encodeURIComponent(slug)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'cancel' }) }); await load(); };
  if (!runId) return <div className="grid h-full place-items-center p-6 text-center"><div><SquareTerminal className="mx-auto mb-3 size-5 text-muted-foreground" /><p className="text-sm font-medium">No workspace open</p><p className="mt-1 text-xs text-muted-foreground">Start a Workspace Run from /work to see Chippi’s files and live execution here.</p></div></div>;
  if (!run) return <div className="p-5 text-xs text-muted-foreground"><Loader2 className="mr-2 inline size-3 animate-spin" />Loading workspace…</div>;
  return <div className="flex h-full min-h-0 flex-col"><div className="border-b border-border/60 px-4 py-3"><div className="flex items-start gap-2"><SquareTerminal className="mt-0.5 size-4" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{run.goal}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{run.status === 'running' ? 'Chippy is working in an isolated workspace.' : run.status}</p></div>{['queued','launching','running'].includes(run.status) && <Button size="xs" variant="ghost" onClick={cancel}><X className="mr-1 size-3" />Cancel</Button>}</div></div><div className="min-h-0 flex-1 overflow-y-auto p-4 space-y-5"><section><p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Live work</p><div className="rounded-lg border border-border/60 bg-muted/[0.18] p-3 font-mono text-[11px] leading-relaxed">{run.events.length ? run.events.map((event) => <div key={event.id} className="mb-2 last:mb-0"><span className="text-muted-foreground/60">{event.sequence.toString().padStart(2,'0')}</span> <span>{event.message}</span>{event.command && <div className="mt-1 text-muted-foreground">$ {event.command}</div>}{event.output && <pre className="mt-1 whitespace-pre-wrap text-muted-foreground">{event.output}</pre>}</div>) : <span className="text-muted-foreground">Waiting for the isolated workspace to start…</span>}</div>{error && <p className="mt-2 text-xs text-destructive">{error}</p>}</section><section><p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Files</p>{run.files.length ? <div className="space-y-1">{run.files.map((file) => <a key={file.id} href={file.fileId ? `/api/workspace-runs/${encodeURIComponent(run.id)}/files/${encodeURIComponent(file.id)}?slug=${encodeURIComponent(slug)}` : undefined} className="flex items-center gap-2 rounded-md px-2 py-1.5 text-xs hover:bg-muted"><FileText className="size-3.5" />{file.name}<span className="ml-auto text-muted-foreground">{Math.max(1, Math.ceil(file.sizeBytes / 1024))} KB</span></a>)}</div> : <p className="text-xs text-muted-foreground">Files will appear here as Chippi creates them.</p>}</section></div><div className="border-t border-border/60 p-3"><Button size="sm" variant="outline" className="w-full" onClick={onContinue}>Continue in chat</Button></div></div>;
}
