-- Persist the seller-pitch narrative generated by composeCmaNarrative
-- (lib/cma-narrative.ts) onto the CmaReport row it was written for, so the
-- pre-listing packet export (app/api/cma/packet/[id]/route.ts) can include it
-- without the browser needing to hold the only copy in memory.
--
-- Nullable: most reports have never had a narrative generated, and the
-- narrative UI + packet route both treat a null narrative as "nothing to
-- show yet" rather than faking one (honest UI — see CLAUDE.md).
--
-- Idempotent / append-only per supabase/migrations conventions: guarded with
-- IF NOT EXISTS so a re-run against an already-migrated database is a no-op.

ALTER TABLE "CmaReport" ADD COLUMN IF NOT EXISTS "narrative" TEXT;
ALTER TABLE "CmaReport" ADD COLUMN IF NOT EXISTS "narrativeUpdatedAt" TIMESTAMPTZ;
